name: Keep App Alive

on:
  schedule:
    - cron: '0 * * * *'  # Ping every 1 hour at the start of the hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render app
        run: |
          curl https://commprep-ai.onrender.com/api/v1/users/keepAlive
